Studio.find_or_create_by!(id: 1, title: "Castle Rock")
Studio.find_or_create_by!(id: 2, title: "MiramaxFilms")
Studio.find_or_create_by!(id: 3, title: "RegencyEnterprises")
Studio.find_or_create_by!(id: 4, title: "Pixar")
Studio.find_or_create_by!(id: 5, title: "Disney")
